### ISSUE TITLE
Fails on bash 4 during pre-commit hook

### ISSUE THREAD

**Issue by joh-m** [awslabs/git-secrets#45]
Hello,

we noticed a problem on bash 4 when multiple files have been changed by a commit.
When getting called in a pre-commit hook we get this error:

`fatal: ambiguous argument 'slides/Container_Network_Model/Body.md slides/Container_Network_Model/Cover.md': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

On bash 3 it works.

It seems like in bash 4 the files argument is passed to the git_grep function with quotes
`git grep -nwHEI --cached '...mypattern...' 'slides/Container_Network_Model/Body.md slides/Container_Network_Model/Cover.md'`

in bash 3 the quotes are not there
`git grep -nwHEI --cached '...mypattern...' slides/Container_Network_Model/Body.md slides/Container_Network_Model/Cover.md`

**Comment by MikeSchuette** [comment]
I'm seeing this same issue on OSX with git-secrets 1.2.1 (from homebrew) under zsh 5.0.8 (also from homebrew).

**Comment by ricoli** [comment]
ping @mtdowling - doesn't look like Travis has been running the tests, or at least not on bash 4...

**Comment by mtdowling** [comment]
I've been looking into this and seeing if I can get a Travis build matrix setup to test against bash 4. I made some progress, but there's still work to be done to get the full matrix actually working an passing.

- Git brach: https://github.com/awslabs/git-secrets/tree/check-cleanup
- Travis build: https://travis-ci.org/awslabs/git-secrets/builds/247375247

I'll keep working at this. Let me know if you or anyone else has feedback on the approach or fixes that can be made.

**Comment by teo-scout24** [comment]
This PR should fix the pre-commit hook error
https://github.com/awslabs/git-secrets/pull/54

**Comment by bjeanes** [comment]
Just hit this as well. Is #54 going to be merged?

**Comment by anna64000** [comment]
Ok thanks

**Comment by teo-scout24** [comment]
Can the maintainers merge this PR please?

**Comment by mtdowling** [comment]
Fixed via #54

**Comment by Eyal-Shalev** [comment]
#54 Does not fix this issue
Running `GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)`
Git Secrets installed via Homebrew `git-secrets: stable 1.2.1 (bottled), HEAD`

Committing a single file (with aws secret) will result in the warning.
Committing multiple files that one of them includes the aws secret will produce the error seen in #65
